### ISSUE TITLE
Maximum or maximum key size?

### ISSUE THREAD

**Issue by relsqui** [BartMassey/ciphersaber2#4]
Quoth the readme:

> ... a key with a **recommended maximum** size of 53 bytes and a **required maximum** size of 256 bytes ...

It seems like either the first one should say "minimum," or else "recommended" and "required" should be swapped, but I don't know which.

**Comment by BartMassey** [comment]
The sentence is actually correct as written, but it took me a minute also. :-)

The key MUST be no more than 256 bytes long. It SHOULD be no more than 53 bytes long.

I would gladly accept a pull request with clarifying language.

**Comment by BartMassey** [comment]
See http://ciphersaber.gurus.org and Google for 53. I did actually typo: the key MUST be no more than 246 bytes long. Only the first 256 bytes of the key will be used by the key scheduling code.  The 10-byte IV is appended to the key, and thus you'll lose part or all of the IV with a longer key, which would be...bad.

Bottom line: 53 bytes is already a ridiculous key length. Don't use more than that.

Please patch.

**Comment by BartMassey** [comment]
OK, I was in there doing something else anyway, so I reworded the README. Please reopen this issue unless you think we're good now.
